remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: [LANDAU + LIFSHITZ ELASTICITY]
description: [We're physicist and we're gonna act like physicists and we're gonna play around like physicists]

